name: windows_virtual_usb
description: Windows Virtual USB Hub — TCP server for USB data stream over SSH tunnel.
version: 1.0.0

environment:
  sdk: ^3.11.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
